name: led_controller
description: Приложение для управления BLE светодиодной лентой.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
